### ISSUE TITLE
Not compatible with irc-16.4-py3.5

### ISSUE THREAD

**Issue by Feandil** [BinetReseau/kaoz#15]
The IRC dependency has changed its model, it does not expose `execute_every` in its reactor anymore:
```
Traceback (most recent call last):
  File "<REDACTED-VENV>/bin/kaoz", line 4, in <module>
    __import__('pkg_resources').run_script('kaoz==2.2.0', 'kaoz')
  File "<REDACTED-VENV>/lib/python3.5/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "<REDACTED-VENV>/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "<REDACTED-VENV>/lib/python3.5/site-packages/kaoz-2.2.0-py3.5.egg/EGG-INFO/scripts/kaoz", line 14, in <module>
    bot.main(sys.argv)
  File "<REDACTED-VENV>/lib/python3.5/site-packages/kaoz-2.2.0-py3.5.egg/kaoz/bot.py", line 103, in main
    notify_systemd=opts.notify_systemd)
  File "<REDACTED-VENV>/lib/python3.5/site-packages/kaoz-2.2.0-py3.5.egg/kaoz/publishbot.py", line 350, in __init__
    *args, **kwargs)
  File "<REDACTED-VENV>/lib/python3.5/site-packages/kaoz-2.2.0-py3.5.egg/kaoz/publishbot.py", line 102, in __init__
    self.reactor.execute_every(self._reconn_interval, self._check_connect)
AttributeError: 'Reactor' object has no attribute 'execute_every'
```

The following patch fixes it for me:
```diff
--- a/kaoz/publishbot.py
+++ b/kaoz/publishbot.py
@@ -99,8 +99,8 @@ class Publisher(irc.client.SimpleIRCClient):
         self._connect_lock = threading.Lock()
         self._has_welcome = False
         self._stop = threading.Event()
-        self.reactor.execute_every(self._reconn_interval, self._check_connect)
-        self.reactor.execute_every(self._line_sleep, self._say_messages)
+        self.reactor.scheduler.execute_every(self._reconn_interval, self._check_connect)
+        self.reactor.scheduler.execute_every(self._line_sleep, self._say_messages)

     def connect(self):
         """Connect to a server"""
```

**Comment by fishilico** [comment]
This is already handled by https://github.com/BinetReseau/kaoz/pull/12 . As the BR does not seems to maintain this project, I will push my fixes upstream directly.
